services:
  # ============================================
  # Stock: PostgreSQL y Backend
  # ============================================
  postgres-stock:
    image: postgres:16.2
    container_name: postgres_main
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_stock_data:/var/lib/postgresql/data
      - ./stock/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./stock/schema.sql:/docker-entrypoint-initdb.d/02-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared_net

  backend-stock:
    image: ghcr.io/frre-ds/2025-grupo-11-backend-stock:f5ff36db6851a291c436acc38baae82805c39c67
    container_name: backend-stock
    environment:
      DB_HOST: postgres-stock
      DB_NAME: stock_management
      DB_USER: postgres
      DB_PASS: postgres
      KEYCLOAK_CLIENT_ID: grupo-11
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ds2025
      KEYCLOAK_DB: keycloak_db
      KEYCLOAK_DB_USER: keycloak_db_user
      KEYCLOAK_DB_PASS: keycloak_db_user_password
      KEYCLOAK_ISSUER: https://keycloak-production-7751.up.railway.app/realms/ds-2025-realm
      KEYCLOAK_CLIENT_SECRET: ef7f0900-8de5-46c0-b813-ce76d61e0158
      KEYCLOAK_REALM: ds-2025-realm
    ports:
      - "3099:3000"
    depends_on:
      postgres-stock:
        condition: service_healthy
    networks:
      - shared_net

  backend-compras:
    image: ghcr.io/frre-ds/backend-compras-g01:7ac7a4efec1f0551fbb8267e391989126ff6b82d
    container_name: backend-compras
    ports:
      - "3081:8081"
    networks:
      - shared_net

  # ============================================
  # API Gateway (Nginx)
  # ============================================
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    restart: always
    ports:
      - "3088:80"
      - "443:443"
    depends_on:
      - backend-compras
      - backend-stock
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - shared_net

volumes:
  mysql_logistica_data:
    driver: local
  postgres_stock_data:
    driver: local

networks:
  shared_net:
    external: true

